### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tanlucvn** [liaojinmin/GeekCodePlus#1]
[16:04:35] [Server thread/ERROR]: Error occurred while enabling GeekCodePlus v3.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/zaxxer/hikari/HikariDataSource
	at me.GeekCodePlus.Libraries.data.MySQL.MySQL.load(MySQL.java:83) ~[?:?]
	at me.GeekCodePlus.Libraries.data.DataBaseManage.start(DataBaseManage.java:28) ~[?:?]
	at me.GeekCodePlus.Libraries.data.DataBaseManage.<init>(DataBaseManage.java:19) ~[?:?]
	at me.GeekCodePlus.GeekCodeMain.onEnable(GeekCodeMain.java:60) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:596) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:309) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: com.zaxxer.hikari.HikariDataSource
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 14 more
[16:04:35] [Server thread/INFO]: [GeekCodePlus] Disabling GeekCodePlus v3.1
[16:04:35] [Server thread/INFO]: [GeekCodePlus] [GeekCodePlus] 再见！

**Comment by tanlucvn** [comment]
Could you please update this plugin? I really love it.
